[package]
       name = "ex03"
    version = "0.1.0"
    authors = ["Jonathan DUFOUR"]
    edition = "2021"
description = "Implementation of our own iterator to iterate over only strictly increasing elements"
