[package]
       name = "ex04"
    version = "0.1.0"
    authors = ["Jonathan DUFOUR"]
    edition = "2021"
description = "Implementation of an iterator to generate prime numbers"

[dev-dependencies]
   primes = "0.3.0"
criterion = "0.5.1"

[[bench]]
   name = "ex04_benchmark"
harness = false