[package]
       name = "ex04"
    version = "0.1.0"
    authors = ["Jonathan DUFOUR"]
    edition = "2021"
description = "Implementation of a more complex already existing trait for our own Time type"
